version: '3'
services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - flyway
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DB=modsen_task
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  flyway:
    image: flyway/flyway
    container_name: flyway
    command: -url=jdbc:postgresql://db:5432/modsen_task -schemas=public -user=postgres -password=postgres migrate
    volumes:
      - ./migration:/flyway/sql
    depends_on:
      - db
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_DB=modsen_task
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: modsen_task